### ISSUE TITLE
Missing silkscreen text on mcu nice nano

### ISSUE THREAD

**Issue by ujl123** [ceoloide/ergogen-footprints#34]
Missing silk screen at the bottom left of the nice nano.  
![image](https://github.com/user-attachments/assets/9992875a-ccbc-4ad3-9f22-559b7e0972a1)

Is this intentional to help users key/align the mcu? Or are those pins not to be used or just mistakenly left off?

**Comment by ceoloide** [comment]
Sorry for the long delay, I was on paternity leave and still working to claw back some free time from my 9 mo baby.

The lack of label is not intentional, and it's a bug. This is a result of trying to have the ability to add or leave out the additional three pins the Nice!Nano has.

**Comment by ceoloide** [comment]
This should now be resolved. both on the missing silkscreen, and the silkscreen appearing on both sides when a single side MCU option is chosen.

To override the single-side silkscreen behavior, there is the `show_silk_labels_on_both_sides` parameter (default `false`).
