### ISSUE TITLE
TRRS footprint "side" parameter doesn't do anything

### ISSUE THREAD

**Issue by monlovesmango** [ceoloide/ergogen-footprints#36]
hey there,

I was working with the trrs footprint and am wanting to mount it on the back. I tried using the `side` parameter but it doesn't seem to actually do anything. 

since the code was already super organized and modularized it was really easy for me to implement the `side` parameter myself. let me know if you'd like a pr for this update. this is my first foray into ergogen and makerjs so would definitely need some review from you.

thanks for all the great footprints and resources! its been immensely helpful to me :)

**Comment by ceoloide** [comment]
Can you paste here the parameters you have used in your config and a screenshot of the PCB? It may be bacause the footprint is through-hole and with symmetric option it just looks the same on both sides.

Be warned I have not tested single-side options as much.

**Comment by ceoloide** [comment]
This is now fixed, thank you for reporting the issue!

<img width="559" alt="Screenshot 2024-10-21 at 10 04 53" src="https://github.com/user-attachments/assets/fd7d1692-8326-4f56-857b-055533bb92e2">

**Comment by monlovesmango** [comment]
thank you for your great footprint library!
